# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-12 09:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=15)),
                ('page', models.CharField(max_length=10)),
                ('user_agent', models.CharField(max_length=255)),
                ('resolution', models.CharField(max_length=10)),
                ('method', models.CharField(max_length=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
