# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-18 12:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='is_view',
            field=models.BooleanField(default=False),
        ),
    ]
