# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-04 12:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20170103_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='order',
            field=models.TextField(default='00000', max_length=100),
            preserve_default=False,
        ),
    ]
