# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-22 15:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_visit_is_view'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='browser_family',
            field=models.CharField(default='Unknown', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='visit',
            name='browser_version',
            field=models.CharField(default='Unknown', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='visit',
            name='device',
            field=models.CharField(default='Unknown', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='visit',
            name='os',
            field=models.CharField(default='Unknown', max_length=50),
            preserve_default=False,
        ),
    ]
